export const KnownMods = [
  'zombie maximum life',
  'lightning damage to attacks', 'physical damage to attacks', 'fire damage to attacks', 'cold damage to attacks',
  'maximum life', 'all elemental resistances', 'cold resistance', 'fire resistance', 'lightning resistance', 'increased evasion rating',
  'increased stun and block recovery', 'dexterity', 'strength', 'intelligence', 'increased lightning damage', 'increased cast speed',
  'increased armour', 'evasion rating', 'mana gained on kill', 'increased mana regeneration rate', 'maximum energy shield',
  'physical attack damage leeched as life', 'maximum mana', 'increased experience gain', 'increased elemental damage', 'accuracy rating',
  'increased physical damage', 'life gained for each enemy hit by attacks', 'increased damage', 'increased global critical strike chance',
  'global critical strike multiplier', 'reduced flask charges used', 'armour', 'reduced attribute requirements',
  'increased rarity of items found', 'physical attack damage leeched as mana', 'all attributes', 'socketed gems are supported by', 'physical damage to melee attackers',
  'chance to block', 'life gained for each enemy hit by your attacks', 'life gained on kill', 'increased cold damage',
  'increased projectile damage', 'increased fire damage', 'increased burning damage', 'chance to ignite', 'life regenerated per second',
  'increased spell damage', 'increased light radius', 'increased chaos damage', 'increased critical strike chance with lightning skills',
  'chaos resistance', 'increased stun duration on enemies', 'increased attack speed', 'increased attack speed with swords',
  'increased ignite duration on enemies', 'increased movement speed', 'increased energy shield', 'increased evasion and energy shield',
  'maximum power charges', 'chance to gain a power charge on kill', 'increased projectile speed', 'reduced number of zombies allowed',
  'increased zombie resistances', 'increased zombie size', 'chance to avoid being stunned', 'reduced stun and block recovery',
  'increased trap damage', 'reduced trap duration', 'traps trigger at the end of their duration', 'socketed gems have elemental equilibrium',
  'reduced elemental equilibrium effect', 'all sockets are white', 'increased critical strike chance', 'chance to gain a power charge when you stun',
  'gain unholy might', 'faster start of energy shield recharge', 'your spells have culling strike',
  'to level of socketed lightning gems', 'to level of socketed fire gems', 'to level of socketed cold gems', 'to level of socketed chaos gems',
  'has 1 socket', 'cannot be inflicted with bleeding', 'increased elemental status ailment duration', 'maximum endurance charges',
  'melee critical strike multiplier', 'increased physical weapon damage while dual wielding', 'increased flask charges gained',
  'increased area damage', 'increased melee damage', 'rare monsters each have a nemesis mod', 'reduced effect on monsters',
  'area contains many totems', 'increased attack and cast speed', 'chaos damage to attacks', 'critical strike multiplier with lightning skills',
  'critical strike multiplier with one handed melee weapons', 'seconds between monster waves', 'waves of monsters',
  'increased weapon critical strike chance while dual wielding', 'increased vaal skill damage', 'increased melee critical strike chance',
  'critical strike multiplier with two handed melee weapons', 'reduced mana cost of skills', 'chance to shock',
  'increased shock duration on enemies', 'critical strike multiplier for spells', 'properties are doubled while in a breach',
  'to level of socketed gems', 'energy shield gained for each enemy hit by your attacks', 'life leech from hits with this weapon applies instantly',
  'causes bleeding on hit', 'reduced life leeched per second', 'power charges on using a warcry',
  'level of socketed warcry gems',
  'reduced energy shield recharge rate',
  'chance to dodge spell damage',
  'increased flask life recovery rate',
  'damage with weapons penetrates',
  'second when you cast a spell',
  'level of socketed spell gems',
  'increased area of effect of area skills',
  'increased endurance, frenzy and power charge duration',
  'increased attack damage',
  'increased area of effect of area skills',
  'increased flask mana recovery rate',
  'chance to cause bleeding enemies to flee on hit',
  'while on low life, enemies are unlucky when damaging you',
  'additional block chance while dual wielding',
  'chaos damage',
  'knockback direction is reversed',
  'block chance applied to spells',
  'increased totem life',
  'ignited enemies you hit are destroyed on kill',
  'maximum frenzy charges',
  'to critical strike multiplier with fire skills',
  'clarity skill',
  'increased flask effect duration',
  'maximum player resistances',
  'less recovery rate of life and energy shield',
  'to monster critical strike multiplier',
  'of elemental damage',
  'to level of socketed minion gems',
  'increased mana cost of skills',
  'increased totem damage',
  'to critical strike multiplier with elemental skills',
  'chance to knock enemies back on hit',
  'reduced attack speed',
  'reduced cast speed',
  'life gained when you block',
  'mana gained when you block',
  'to maximum block chance',
  'chance to be ignited',
  'reduced light radius',
  'increased chill duration on enemies',
  'reduced enemy stun threshold',
  'to all maximum resistances while you have no endurance charges',
  'to level of socketed bow gems',
  'chance to cause bleeding on hit',
  'reduced mana regeneration rate',
  'reduced duration of curses on you',
  'increased block recovery',
  'reduced spell damage',
  'increased attribute requirements',
  'additional totem summoned at a time',
  'curse on you when your totems die',
  'reduced movement speed',
  'to weapon range',
  'to level of socketed aura gems',
  'reduced mana reservation',
  'increased area of effect of aura skills',
  'increased effect of non-curse auras you cast',
  'chance to cause monsters to flee',
  'flammability skill',
  'increased mana leeched per second per equipped corrupted item',
  'bone nova when you kill a bleeding enemy',
  'increased trap throwing speed',
  'to maximum number of spectres',
  'of their value',
  'increased global attack speed per green socket',
  'to melee weapon range per white socket',
  'mana regenerated per second',
  'chance to poison on hit',
  'to maximum number of skeletons',
  'reduced rarity of items found',
  'reduced reflected elemental damage taken',
  'to mana cost of skills',
  'to level of socketed curse gems',
  'increased curse duration',
  'chance to freeze while using a flask',
  'life gained for each enemy hit by your spells',
  'to melee weapon and unarmed range',
  'reduced mana cost per endurance charge',
  'reduced damage when on low life',
  'chance to gain a power charge on throwing a trap',
  'bear trap skill',
  'of damage taken gained as mana when hit',
  'anger skill',
  'reduced ignite duration on enemies',
  'life per second',
  'increased minion attack and cast speed per skeleton you own',
  'increased minion duration per zombie you own',
  'increased minion damage per spectre you own',
  'reduced experience gain',
  'haste skill',
  'increased quantity of items found',
  'chance to cause monster to flee on block',
  'chance to avoid being shocked',
  'additional trap placed at a time',
  'mana gained for each enemy hit by your attacks',
  'increased mine damage',
  'increased freeze duration on enemies',
  'chance to freeze',
  'to critical strike multiplier while dual wielding',
  'additional maps',
  'increased experience',
  'seconds',
  'reduced freeze duration on you',
  'manifest dancing dervish on rampage',
  'increased skeleton duration',
  'to maximum number of zombies',
  'increased effect of your curses',
  'increased effect of flasks',
  'reduced area of effect of curse skills',
  'chance to cause bleeding',
  'chance to poison the enemy',
  'increased skill effect duration',
  'reduced mana reserved',
  'reduced effect on you',
  'to level of socketed support gems',
  'icestorm skill',
  'reduced projectile speed',
  'chance to blind enemies on hit',
  'of attack damage leeched as life on critical strike',
  'chance to avoid being frozen',
  'chance to gain a power charge on hit',
  'chance to blind enemies on critical strike',
  'additional projectiles',
  'of attack damage leeched as life against bleeding enemies',
  'reduced damage',
  'increased area of effect of curse skills',
  'increased effect of curses on them',
  'chance to grant onslaught to nearby enemies on kill',
  'chance to grant unholy might to nearby enemies on kill',
  'additional golem at a time',
  'summon stone golem',
  'increased effect of auras on you',
  'increased effect of auras on your minions',
  'increased shock duration on you',
  'increased totem placement speed',
  'of attack damage leeched as life',
  'more rare monsters',
  'more monster life',
  'reduced flask charges',
  'increased life leeched per second',
  'chance to grant a power charge to nearby allies on kill',
  'chance to grant a frenzy charge to nearby allies on hit',
  'reduced effect of curses on you',
  'elemental resistances while using a flask',
  'and below',
  'chance to avoid being ignited',
  'chance of projectiles piercing',
  'increased herald of thunder buff effect',
  'increased rarity of items dropped by frozen enemies',
  'chance to gain an endurance charge when you block',
  'extra damage as lightning',
  'reduced attack and cast speed per frenzy charge',
  'chance to gain a frenzy charge on kill',
  'of damage is taken from mana before life',
  'additional rogue exiles',
  'increased item rarity',
  'increased mana reserved',
  'increased life leeched per second per equipped corrupted item',
  'more damage over time',
  'reduced quantity of items found',
  'to critical strike multiplier with cold skills',
  'chance to create chilled ground when hit with an attack',
  'energy shield gained on kill per level',
  'blasphemy',
  'reduced character size',
  'chance to taunt on hit',
  'to level of socketed golem gems',
  'reduced totem damage',
  'fire attack damage per buff on you',
  'fire spell damage per buff on you',
  'of attack damage leeched as mana',
  'increased stun duration on you',
  'reduced frenzy charge duration',
  'additional block chance',
  'additional chance to receive a critical strike',
  'chance on block to create consecrated ground',
  'less area of effect',
  'increased projectile attack damage',
  'increased character size',
  'assassin\'s mark skill',
  'chance to avoid being chilled',
  'additional arrows',
  'mana gained for each enemy hit by attacks',
  /* cast a spell on kill mod??  Mods here need addressed */
  'additional curse',
  'you gain onslaught for',
  'chance to cast', 'curse enemies', 'zombies deal',
  /* 3 mods added to weapon damage need a better detection */
  'fire damage to spells', 'cold damage to spells', 'lightning damage to spells',
  'fire damage', 'cold damage', 'lightning damage', 'physical damage'
]
